export interface Classes {
  root: string[],
  label: string[],
  labelTitle: string[],
  labelCounter: string[],
  labelCounterNumber: string[],
  labelCounterIcon: string[],
  labelChevronIcon: string[],
  labelLoadingIcon: string[],
  labelChevronIconOpen: string[],
  dropdown: string[],
  options: string[],
  option: string[],
  optionLabel: string[],
  optionIcon: string[],
}
